name: Autoconfigure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Get Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Cargo Check"
        run: cargo check

      - name: "Cargo Build"
        run: cargo build --release --all-features


